CREATE TABLE [dbo].[Users]
(
	[Id] INT IDENTITY (1, 1) NOT NULL,
	[Name] VARCHAR(200) NOT NULL,
	[LastName] VARCHAR(200) NOT NULL,
	[Mail] VARCHAR(100),
	[Password] VARCHAR(50) NOT NULL,
	CONSTRAINT [PK_UserId] PRIMARY KEY CLUSTERED ([Id] ASC)
)
